In [ ]:
df = pd.read_csv('/content/drive/MyDrive/salaries_by_college_major.csv')

In [ ]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [ ]:
clean_df = df.dropna()

In [ ]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [ ]:
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [ ]:
clean_df['Starting Median Salary'].idxmax()

43

In [ ]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [ ]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [ ]:
clean_df['Mid-Career Median Salary'].idxmax()

8

In [ ]:
clean_df['Undergraduate Major'][8]

'Chemical Engineering'

In [ ]:
clean_df['Starting Median Salary'].loc[8]

63200.0

In [ ]:
clean_df['Starting Median Salary'].idxmin()

49

In [ ]:
clean_df['Undergraduate Major'][49]

'Spanish'

In [ ]:
clean_df['Starting Median Salary'].idxmin()

49

In [ ]:
clean_df['Starting Median Salary'][49]

34000.0

In [ ]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [ ]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]['Undergraduate Major']

'Education'

In [ ]:
print(clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]['Undergraduate Major'])

Education

In [ ]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

In [ ]:
spread_col

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [ ]:
clean_df.insert(6, 'Spread Risk', spread_col)

In [ ]:
clean_df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Spread Risk
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business,109800.0
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM,96700.0
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business,113700.0
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS,104200.0
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business,85400.0

In [ ]:
low_risk = clean_df.sort_values('Spread Risk')

In [ ]:
low_risk[['Undergraduate Major', 'Spread Risk']].head()

           Undergraduate Major  Spread Risk
40                     Nursing      50700.0
43         Physician Assistant      57600.0
41                   Nutrition      65300.0
49                     Spanish      65400.0
27  Health Care Administration      66400.0

In [ ]:
high_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False).head()

In [ ]:
high_potential

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Spread Risk
17,Economics,50100.0,98600.0,50600.0,210000.0,Business,159400.0
22,Finance,47900.0,88300.0,47200.0,195000.0,Business,147800.0
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM,122100.0
37,Math,45400.0,92400.0,45200.0,183000.0,STEM,137800.0
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM,122000.0

In [ ]:
high_potential[['Undergraduate Major','Mid-Career Median Salary']]

     Undergraduate Major  Mid-Career Median Salary
17             Economics                   98600.0
22               Finance                   88300.0
8   Chemical Engineering                  107000.0
37                  Math                   92400.0
44               Physics                   97300.0

In [ ]:
highest_spread = clean_df.sort_values('Mid-Career Median Salary', ascending=False)

In [ ]:
highest_spread[['Undergraduate Major', 'Spread Risk']].head()

       Undergraduate Major  Spread Risk
8     Chemical Engineering     122100.0
12    Computer Engineering      95900.0
19  Electrical Engineering      98700.0
1    Aerospace Engineering      96700.0
17               Economics     159400.0

In [ ]:
clean_df.groupby('Group').count()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Spread Risk
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [ ]:
clean_df.groupby('Group').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
clean_df.groupby('Group').head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Spread Risk
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business,"109,800.00"
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM,"96,700.00"
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business,"113,700.00"
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS,"104,200.00"
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business,"85,400.00"
5,Art History,"35,800.00","64,900.00","28,800.00","125,000.00",HASS,"96,200.00"
6,Biology,"38,800.00","64,800.00","36,900.00","135,000.00",STEM,"98,100.00"
7,Business Management,"43,000.00","72,100.00","38,800.00","147,000.00",Business,"108,200.00"
8,Chemical Engineering,"63,200.00","107,000.00","71,900.00","194,000.00",STEM,"122,100.00"
9,Chemistry,"42,600.00","79,900.00","45,300.00","148,000.00",STEM,"102,700.00"
10,Civil Engineering,"53,900.00","90,500.00","63,400.00","148,000.00",STEM,"84,600.00"
11,Communications,"38,100.00","70,000.00","37,500.00","143,000.00",HASS,"105,500.00"
14,Construction,"53,700.00","88,900.00","56,300.00","171,000.00",Business,"114,700.00"
15,Criminal Justice,"35,000.00","56,300.00","32,200.00","107,000.00",HASS,"74,800.00"
16,Drama,"35,900.00","56,900.00","36,700.00","153,000.00",HASS,"116,300.00"

In [ ]:
numeric_columns = ['Starting Median Salary', 'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary', 'Mid-Career 90th Percentile Salary', 'Spread Risk']  # Define numeric_columns

In [ ]:
clean_df.groupby('Group')[numeric_columns].mean()

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Spread Risk
Group,,,,,
Business,"44,633.33","75,083.33","43,566.67","147,525.00","103,958.33"
HASS,"37,186.36","62,968.18","34,145.45","129,363.64","95,218.18"
STEM,"53,862.50","90,812.50","56,025.00","157,625.00","101,600.00"